### ISSUE TITLE
Use embedded HidUsageTables.json when available

### ISSUE THREAD

**Issue by desowin** [IntergatedCircuits/hid-usage-tables#5]
Since version 1.3 (Issue Date January 1, 2022), HID Usage Tables for Universal Serial Bus includes embedded HidUsageTables.json file. It is preferred to use the JSON file as opposed to page text scanning.

**Comment by benedekkupper** [comment]
Which would question the entire existence of this repository frankly. The reasons why I'm reluctant to do that are listed in [this discussion](https://github.com/IntergatedCircuits/hid-usage-tables/issues/4#issuecomment-1238639008). Although I do plan to create a converter that generates the pages in this format from the json input for comparison.

**Comment by benedekkupper** [comment]
This is now implemented, you can parse the database from the embedded JSON instead from this source:
```
    # hid_pages = parse_database()
    hid_pages = parse_json(path_to_json_file)
```
You still need to download the PDF, and extract the JSON from it, so this is not set as the default method.
